//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    public partial class OnboardingEntities : DbContext
    {
        public OnboardingEntities()
            : base("name=OnboardingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual ObjectResult<string> Csp_GetMobileNo(int reqId)
        {
            var reqIdParameter = reqId != null ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Csp_GetMobileNo", reqIdParameter);
        }


        public virtual int Csp_UpdateMobileNo(int reqId, string mobileNo, string modifiedBy)
        {
            var reqIdParameter = reqId != null ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Csp_UpdateMobileNo", reqIdParameter, mobileNoParameter, modifiedByParameter);
        }


        public virtual DbSet<V_CostCtrCd> V_CostCtrCd { get; set; }
        public virtual DbSet<V_GenderCd> V_GenderCd { get; set; }
        public virtual DbSet<V_OffTask> V_OffTask { get; set; }
        public virtual DbSet<V_OffTaskAttrb> V_OffTaskAttrb { get; set; }
        public virtual DbSet<V_OffTaskLog> V_OffTaskLog { get; set; }
        public virtual DbSet<V_RaceCd> V_RaceCd { get; set; }
        public virtual DbSet<V_Req> V_Req { get; set; }
        public virtual DbSet<V_ReqAtt> V_ReqAtt { get; set; }
        public virtual DbSet<V_ReqAttrbCd> V_ReqAttrbCd { get; set; }
        public virtual DbSet<V_ReqEmp> V_ReqEmp { get; set; }
        public virtual DbSet<V_ReqLog> V_ReqLog { get; set; }
        public virtual DbSet<V_ReqOffAttrb> V_ReqOffAttrb { get; set; }
        public virtual DbSet<V_ReqStsCd> V_ReqStsCd { get; set; }
        public virtual DbSet<V_ReqSysAccAttrb> V_ReqSysAccAttrb { get; set; }
        public virtual DbSet<V_ReqTypeCd> V_ReqTypeCd { get; set; }
        public virtual DbSet<V_SalutCd> V_SalutCd { get; set; }
        public virtual DbSet<V_SysAccTask> V_SysAccTask { get; set; }
        public virtual DbSet<V_SysAccTaskAttrb> V_SysAccTaskAttrb { get; set; }
        public virtual DbSet<V_SysAccTaskLog> V_SysAccTaskLog { get; set; }
        public virtual DbSet<V_TaskAgent> V_TaskAgent { get; set; }
        public virtual DbSet<V_TaskAttrbCd> V_TaskAttrbCd { get; set; }
        public virtual DbSet<V_TaskCd> V_TaskCd { get; set; }
        public virtual DbSet<V_TaskDep> V_TaskDep { get; set; }
        public virtual DbSet<V_TaskStsCd> V_TaskStsCd { get; set; }
        public virtual DbSet<V_UserSubTypeCd> V_UserSubTypeCd { get; set; }
        public virtual DbSet<V_UserTypeCd> V_UserTypeCd { get; set; }
    }
}
