//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PATRONEntities : DbContext
    {
        public PATRONEntities()
            : base("name=PATRONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_OnboardingPerInfo> V_OnboardingPerInfo { get; set; }
        public virtual DbSet<V_OnboardingCostCtrCd> V_OnboardingCostCtrCd { get; set; }
        public virtual DbSet<V_OnboardingGenderCd> V_OnboardingGenderCd { get; set; }
        public virtual DbSet<V_OnboardingRaceCd> V_OnboardingRaceCd { get; set; }
        public virtual DbSet<V_OnboardingSalutCd> V_OnboardingSalutCd { get; set; }
    }
}
