//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecAccEntities : DbContext
    {
        public SecAccEntities()
            : base("name=SecAccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_GetSysUserProg> V_GetSysUserProg { get; set; }
        public virtual DbSet<V_GetSysUserProgData> V_GetSysUserProgData { get; set; }
    }
}
