//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetSysUserProg
    {
        public string sys_id { get; set; }
        public string prog_id { get; set; }
        public string user_id { get; set; }
        public string prog_nm { get; set; }
        public string user_nm { get; set; }
        public string dept_c { get; set; }
        public string dept_t { get; set; }
        public string active_f { get; set; }
    }
}
