//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetSysUserProgData
    {
        public string sys_id { get; set; }
        public string prog_id { get; set; }
        public string user_id { get; set; }
        public string sec_tp_cd { get; set; }
        public string data_param { get; set; }
    }
}
