//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OffTaskLog
    {
        public int OffTaskLogId { get; set; }
        public int OffTaskId { get; set; }
        public string ChangeBy { get; set; }
        public System.DateTime ChangeDt { get; set; }
        public string FieldNm { get; set; }
        public string FromVal { get; set; }
        public string ToVal { get; set; }
    }
}
