//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OffTask
    {
        public int OffTaskId { get; set; }
        public int ReqId { get; set; }
        public string TaskCd { get; set; }
        public string TaskStsCd { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDt { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
    }
}
