//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Req
    {
        public int ReqId { get; set; }
        public string ReqTypeCd { get; set; }
        public string FirstNm { get; set; }
        public string LastNm { get; set; }
        public string PrefNm { get; set; }
        public string SalutCd { get; set; }
        public string GenderCd { get; set; }
        public string RaceCd { get; set; }
        public string PrsnEmail { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsExistingStaff { get; set; }
        public Nullable<bool> IsExSmuStd { get; set; }
        public string ReqStsCd { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsAmended { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
    }
}
