//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ReqOffAttrb
    {
        public int ReqOffAttrbId { get; set; }
        public int ReqId { get; set; }
        public string ReqAttrbCd { get; set; }
        public string ReqAttrbVal { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
    }
}
